version: '3'

services:

  server-alpha:
    build: ./build
    ports:
      - "3000:3000"
      - "3003:3003"
      - "3033:3033"
    environment:
      - NAME=alpha

  server-beta:
    build: ./build
    ports:
      - "4000:4000"
      - "4004:4004"
      - "4044:4044"
    environment:
      - NAME=beta

  server-gamma:
    build: ./build
    ports:
      - "5000:5000"
      - "5005:5005"
      - "5055:5055"
    environment:
      - NAME=gamma

  server-delta:
    build: ./build
    ports:
      - "8000:8000"
      - "8008:8008"
      - "8088:8088"
    environment:
      - NAME=delta